# use latest Node LTS (Erbium)
# FROM node:erbium
FROM node:8.17.0
ENV FIREBASE_TOKEN [YOUR FIREBASE TOKEN]
# install Firebase CLI
RUN npm install -g firebase-tools

ENTRYPOINT ["/usr/local/bin/firebase"]